import Link from "next/link";
import {supabase} from "../lib/supabase";

const categories=[["Anime News","anime-news"],["Episode Guides","episode-guides"],["Characters","characters"],["Explained","explained"],["Watch Guides","watch-guides"],["Rankings","rankings"],["Manga","manga"],["Recommendations","recommendations"]];

async function getArticles(){const {data}=await supabase.from("articles").select("id,title,slug,excerpt,featured_image,published_at,categories(name,slug)").eq("status","published").order("published_at",{ascending:false}).limit(12);return data||[]}

export default async function Home(){const articles=await getArticles();return <main>
<header className="border-b border-white/10 sticky top-0 bg-[#08090d]/95 backdrop-blur z-10"><div className="container h-16 flex items-center justify-between"><Link href="/" className="text-2xl font-black tracking-tight">ANIME<span className="text-fuchsia-400">HUB</span></Link><nav className="hidden lg:flex gap-5 text-sm text-white/70">{categories.slice(0,5).map(([n,s])=><Link key={s} href={"/"+s} className="hover:text-white">{n}</Link>)}</nav></div></header>
<section className="container pt-20 pb-14"><p className="text-fuchsia-400 font-bold uppercase tracking-[.2em] text-xs">Your anime search destination</p><h1 className="mt-4 text-5xl md:text-7xl font-black max-w-4xl leading-[.95]">Anime news, guides & stories worth knowing.</h1><p className="mt-6 text-lg text-white/60 max-w-2xl">Find episode guides, character explanations, watch orders, rankings, manga updates and the answers anime fans actually search for.</p></section>
<section className="container pb-16"><div className="flex flex-wrap gap-2">{categories.map(([n,s])=><Link key={s} href={"/"+s} className="px-4 py-2 rounded-full border border-white/10 bg-white/[.03] text-sm hover:bg-white/10">{n}</Link>)}</div></section>
<section className="container pb-24"><div className="flex items-end justify-between mb-6"><div><p className="text-xs uppercase tracking-widest text-white/40">Latest</p><h2 className="text-3xl font-bold mt-1">Latest anime stories</h2></div></div>{articles.length===0?<div className="rounded-2xl border border-white/10 p-10 text-white/50">The first stories are being prepared. The site is connected to its editorial database.</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{articles.map(a=><article key={a.id} className="rounded-2xl border border-white/10 bg-white/[.025] overflow-hidden hover:border-fuchsia-400/40 transition">{a.featured_image&&<img src={a.featured_image} alt="" className="w-full aspect-video object-cover"/>}<div className="p-5"><p className="text-xs text-fuchsia-400 font-semibold">{a.categories?.name||"Anime"}</p><h3 className="text-xl font-bold mt-2"><Link href={"/article/"+a.slug}>{a.title}</Link></h3><p className="mt-3 text-sm text-white/55">{a.excerpt}</p><p className="mt-5 text-xs text-white/35">{a.published_at?new Date(a.published_at).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):""}</p></div></article>)}</div>}</section>
<footer className="border-t border-white/10"><div className="container py-10 text-sm text-white/40">© {new Date().getFullYear()} Anime Hub. Independent anime coverage, guides and explanations.</div></footer>
</main>}